### ISSUE TITLE
JSON output not correctly escaping non-Unicode characters

### ISSUE THREAD

**Issue by mchro** [edenhill/kcat#196]
The JSON RFC has this range of unescaped characters for strings:
`      unescaped = %x20-21 / %x23-5B / %x5D-10FFFF`
but also the text "All Unicode characters may be placed within the quotation marks".

In yajl there is this code: https://github.com/lloyd/yajl/blob/5e3a7856e643b4d6410ddc3f84bc2f38174f2872/src/yajl_encode.c#L61
which is correctly escaping below 0x20, but characters above 0x80 are not escaped. Characters above 0x80 however need to be escaped to be proper Unicode, quoting  https://en.wikipedia.org/wiki/C0_and_C1_control_codes: "The C1 codes require two bytes to be encoded in UTF-8".

So the code in yayl should be updated to also escape characters above 0x80.

If you can point me in the direction of the yajl library being used, I would gladly supply a patch.

**Comment by edenhill** [comment]
Use my fork to begin with, so we don't need to wait for a new upstream release:

https://github.com/edenhill/yajl

But do file a PR upstream aswell
