### ISSUE TITLE
Not able to read schema registry credentials from file 

### ISSUE THREAD

**Issue by bluedog13** [edenhill/kcat#342]
I have the config file for the cluster and the schema registry in the file as below
```
bootstrap.servers=********:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=********
sasl.password=********************
schema.registry.url=https://********.azure.confluent.cloud
basic.auth.credentials.source=USER_INFO
basic.auth.user.info=********************
```

Below is the command I am using to run kafkacat
```
kafkacat -C \
     -F /path/to/config-file \
     -t my-topic \
     -s avro \
     -e \
     -f '\nKey (%K bytes): %k
         Value (%S bytes): %s
         Timestamp: %T
         Partition: %p
         Offset: %o
         Headers: %h\n--\n'
```

I see the below error
```
% Reading configuration from file ./configs/*********.config
% ERROR: ./configs/*********.config:8: No such configuration property: "basic.auth.credentials.source"
```

How can the below  resolved?
1. How do we connect to schema registry and validate the credentials?

Thanks.

**Comment by edenhill** [comment]
Put the SR user and password in the SR URL, like so:
`schema.registry.url=https://user:pass@..some.server.cloud`

**Comment by james00002** [comment]
Sorry I know this is an old issue, but what do you do when the username or password contain @ or : characters? I can't figure out a working way to escape those characters in the schema.registry.url=https://user:pass@..some.server.cloud format
