### ISSUE TITLE
kcat consumer adds one character to the end of consumed binary message

### ISSUE THREAD

**Issue by hansut** [edenhill/kcat#344]
Hello,

we would like to use kcat to copy messages from one topic to another. Our messages are encoded in Protobuf format and we need kcat to just copy the binary data and not modify it. 

When we tried to consume a message and save it to file, it seems kcat adds one character to the end of the message, making it unreadable for the Protobuf deserializer. Our message in topic has 142 bytes, but saved to the disc, it has 143 bytes. When we print the saved message using 'cat' command, it seems like newline character was added.

We are using following command:

`kcat -C -b localhost:9092 -o -1 -e -t test_topic > saved_message.bin`

Can you please advise how to achieve our goal to just save the original payload of the message?

Thank you in advance.
Tomas

**Comment by edenhill** [comment]
The default message delimiter (-D) is `\n`. Try `-D ""`.

**Comment by hansut** [comment]
Thank you, it is working now.
