### ISSUE TITLE
How does the kcat output buffer work?

### ISSUE THREAD

**Issue by b1zzu** [edenhill/kcat#352]
Hi,
I'm trying to understand how does kcat buffer the output before writing it to stdout when running in consuming mode.

What is my problem:
When I run kcat from a standard terminal (Gnome Terminal + zsh) in consuming mode the messages are printed on the terminal almost in real-time, but when I run kcat as a Java subprocess the output-stream (stdout)  doesn't receive any messages until a SIGINT is sent to the kcat process and then all the messages are flushed to the stdout.

I found out is possible to disable the kcat buffer using `-u` option and it works but how the buffer is working is not explained or I can't find it.

Some of the questions I have regarding it are:
- What is the buffer size?
- Does it have a flush timeout?
- Is it possible to force kcat to flush the buffer while is running?

**Comment by edenhill** [comment]
kcat relies on the standard libc stdio buffering (`man stdio`) and all `-u` does is call `setbuf(stdout, NULL)` to disable all output buffering.

**Comment by b1zzu** [comment]
Thanks @edenhill
