### ISSUE TITLE
About 1.7.1 release

### ISSUE THREAD

**Issue by chenrui333** [edenhill/kcat#364]
👋  it looks like 1.7.1 is still not marked as the latest release, raise this issue to double confirm it. Thanks!

- relates to https://github.com/Homebrew/homebrew-core/pull/93419

**Comment by edenhill** [comment]
The only change in 1.7.1 is to update librdkafka in the edenhill/kcat **docker** image.
There's no need to release a new homebrew package (and I'm not responsible for that anyway).

**Comment by chenrui333** [comment]
Thanks for clarifying the change list, but I do think it might be a good idea to write some release notes as there is release tag in the repo though. Let me know what you think.
