### ISSUE TITLE
kcat seems to add extraneous carriage returns '\r' to byte output

### ISSUE THREAD

**Issue by aarashy** [edenhill/kcat#368]
### What's wrong?
I was trying to use kcat to print the raw bytes of my Kafka message payload value. 

Surprisingly, the bytes returned by kcat seem to be wrong by adding exactly 4 extraneous carriage returns (hexadecimal 0x0D, decimal 13)

### Repro
Here is the command that I'm using. It pipes the output of kcat into hexdump, which formats the bytes as comma-separated unsigned decimals.

```
docker run --network=host -it --rm edenhill/kcat:1.7.1 -b localhost:9092 -C  -c1 -f '%s' -t <topicname> | hexdump -e'16/1 "%03u, "'
```

I built my own simple CLI tool that prints raw kafka bytes from a topic. You can invoke it with the following:

```
docker run --net=host --rm aarashy/kafkabyter:latest consume -s localhost:9092 -c 1 -o 0 -p 0 -t $MYTOPIC print-json
```

#### Result
Here's a screenshot of the diff. My tool is on the left and kcat's output is on the right. I'm sure my tool is correct because it matches my producer's bytes exactly. 

<img width="1830" alt="Screen Shot 2022-02-10 at 4 05 40 PM" src="https://user-images.githubusercontent.com/12239115/153496523-d976c949-f11f-4e37-9c3a-5681b42f79e3.png">

I expected kcat's output not to have these extraneous carriage returns. Is anybody else experiencing this?
Is this a bug?

**Comment by aarashy** [comment]
```
pub async fn print_kafka_messages(opt: Opt) -> Result<(), anyhow::Error> {
    let consumer = create_kafka_consumer(&opt)?;

    for _ in 0..opt.count {
        let message = consumer.recv().await?;
        let offset = message.offset();

        let payload = match message.payload() {
            Some(bytes) => bytes,
            None => {
                eprintln!("Kafka message at offset {} has no payload", offset);
                &[]
            }
        };

        let output_json = {
            let timestamp_millis = message.timestamp().to_millis();
            let payload_byte_len = payload.len();
            json!({
                "payload": payload,
                "kafkaPublishTimestampMilliseconds": timestamp_millis,
                "offset": offset,
                "payloadByteLen": payload_byte_len
            })
        };

        println!("{}", output_json.to_string());
    }

    Ok(())
}
```
In case it helps, here's a snippet of the rust program I'm using in my CLI tool mentioned above. 
As you can see, it's really just taking the raw byte payload of the message and printing it.

**Comment by edenhill** [comment]
Can't reproduce:
```bash
# produce
bash-3.2$ echo -n "12345" | ./kcat -b $BROKERS -P -t test -p 0

# consume
bash-3.2$ ./kcat -b $BROKERS -C -t test -p 0 -e -f '%s' | hexdump -C
% Reached end of topic test [0] at offset 1: exiting
00000000  31 32 33 34 35                                    |12345|
00000005

# produce with key
bash-3.2$ echo -n "mykey:myvalue" | ./kcat -b $BROKERS -P -t test -p 0 -K:

# consume again
bash-3.2$ ./kcat -b $BROKERS -C -t test -p 0 -e -f '%s' | hexdump -C
% Reached end of topic test [0] at offset 2: exiting
00000000  31 32 33 34 35 6d 79 76  61 6c 75 65              |12345myvalue|
0000000c
bash-3.2$
```

**Comment by aarashy** [comment]
Thanks for looking! My input was non-utf8 strings. Let me see if I can construct a reproducible example.

**Comment by aarashy** [comment]
Hi Magnus, could you please try this example?

What's crucial about this example is that it uses the newline character (decimal value 10, hex 0x0a).
If you look at my screenshot above, all of the extraneous `13` / carriage return were added in front of `10` / newline. I believe the example below is a consistent repro of this.

```
echo -n "CgMYtAo=" | base64 -d | hexdump -e '16/1 "%u " " "'

>>> Returns `10 3 24 180 10`
```

```
# Publish
echo -n "CgMYtAo=" | base64 -d | docker run --network=host -i --rm edenhill/kcat:1.7.1 -b $BROKERS -P -D random-delimiter -t mytopictest

# Consume to echo what was published
docker run --network=host -it --rm edenhill/kcat:1.7.1 -b localhost:9092 -C -c1 -e -f '%s' -t $TESTTOPIC | hexdump -e '16/1 "%u " "\n"'

>>> Unexpectedly returns `13 10 3 24 180 13 10`
```

**Comment by aarashy** [comment]
Ahh... yes that's it. When I docker run without the -t flag the problem goes away. 
Good to know that I should be careful using the -t.
