### ISSUE TITLE
Update Ubuntu and Debian installation instructions to use official kafkacat packages.

### ISSUE THREAD

**Issue by CodyKochmann** [edenhill/kcat#370]
The `README.md` suggests under Debian / Ubuntu installation instructions to custom build the package using make.

The following appears to be valid in both OS's package managers on their `stable` versions with no additional modifications. 😄 

```bash
apt install kafkacat
```

**Comment by edenhill** [comment]
The Deb/Ubuntu packages are typically quite outdated though.

**Comment by aidan-melen** [comment]
Can we please update the Deb/Ubuntu packages to version 1.7.0? It would be great to have the new AVRO support in those packages.

**Comment by edenhill** [comment]
Those packages are not maintained by this project, but by Debian maintainers.
